- hosts: test
  tasks:
         - name: Installing httpd package
           package:
              name: httpd
              state: absent
         - name: starting the service
           service:
              name: httpd
              state: stopped
