- hosts: my_lb
  vars_files:
          - haproxy_vars.yml
  tasks:
          - name: installing haproxy
            package:
                    name: haproxy
                    state: present
            vars:
                    ansible_python_interpreter: /usr/bin/python
          - name: copying haproxy.cfg
            template:
                    src: haproxy.cfg
                    dest: /etc/haproxy/haproxy.cfg
          - name: starting services
            service:
                    name: haproxy
                    state: restarted
